package exceptionTest02;

import java.util.Scanner;

// 14번 : 메소드 선언부에서의 throws
public class ThrowsTest02 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		method(sc);
	}
	
	static void method(Scanner sc) {
		System.out.println("양수만 입력하세요!!");
		int result = sc.nextInt();
		if(result <= 0) {
			System.out.println("다시 입력하세요 양수만 입력가능");
		}
		System.out.println("입력한 숫자는 " + result + "입니다");
		
		
		
	}
	
}
